spring:
  application:
    name: sec_crud
  profiles:
    active: dev,db
---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env.dev[.properties]
  thymeleaf:
    cache: false
